### ISSUE TITLE
Implement jump action

### ISSUE THREAD

**Issue by fredyvilla** [fredyvilla/opencog-to-minecraft#12]
Ability to jump over blocks.

**Comment by AndrewBuck** [comment]
The jump action is already implemented.  When you tell the bot to move you pass it a boolean variable telling it whether it should jump or not.  Basically what really needs to be done is decide when moving needs a jump and when it does not and then just pass this to the move function we are already calling.

**Comment by kdexd** [comment]
Ok, so we must get the information about the adjacent blocks to the position of bot, and trigger jump if the random direction decided has one block higher than the boy's current ground. Where should I look upon in the code to start?
I wish to have a good tour of the source to know what part of code does what job. This task will be appropriate for me if it is beginner level.

**Comment by AndrewBuck** [comment]
Your analysis is correct, however the actual thing we need to do is implement a proper pathfinding algorithm in the blockspace that actually computes and stores (in the atomspace) a path of blocks to get from some starting point to some ending point.  The stored result should be a List node which contains a single long list where every list item is either the next block to move to or a jump instruction.

This kind of routing is a lot more useful and is what we need to do in the long run anyway so I think it makes sense to add this instead, rather than refining the existing "move 1 block randomly" code.

**Comment by AndrewBuck** [comment]
I created a new issue 18 for this routing algorithm as it is a core thing that needs to be done.  I think this one could probably be closed out in favor of that one.

**Comment by kdexd** [comment]
Yes, a routing algorithm can be worked upon. Implementing a jump action should be included within that issue. I agree to the fact that this issue can be closed in favor of #18 . Further discussions there.

**Comment by AndrewBuck** [comment]
Closing to move to #18
