### ISSUE TITLE
Ability to consume items

### ISSUE THREAD

**Issue by fredyvilla** [fredyvilla/opencog-to-minecraft#9]
Ability to select an item from quick bar and try to consume it (typically right-clicking)

**Comment by AndrewBuck** [comment]
The spockbot plugin for doing that kind of stuff is the Interact plugin.  The digging code is also in the interact, but I ended up copying the digging code to the opencog codebase rather than calling the spockbot functions.  We should figure out the best way of interfacing with spockbot like this.  Our implementation is somewhat different because we have ROS driving it, but it should be possible to do this in general.

Here is the function you want to eat the thing in the currently active hotbar slot.  We need to set up message pipelines for interacting with the inventory system to move things around and select a particular item, and then a separate pipeline for sending the actual eating signal.  The pipelines are not too difficult to build, but we also need to come up with a good way of doing this since we will need a lot of these things.

https://github.com/SpockBotMC/SpockBot/blob/7747f01fceaa4d575ee1f6e34dc01ac8566c7c3c/spockbot/plugins/helpers/interact.py#L176
